# You can name this whatever you want
name: update realtime

# You will get an error on the automatic updates committing
# if you do not have this line
# You didn't need it before, which is why a lot of yml job files
# you see will not have it (but you need it now!!!)
permissions:
  contents: write

# The 'on' section is about when this is run
# workflow_dispatch makes there be a button on GitHub to let you run it manually
# schedule and cron make it run at certain frequencies
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:


jobs:
  forecast-update:
    name: python
    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Update realtime
        run: uv run python -m src.forecast_ui --update realtime
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Commit and push any changes
        run: |-
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
