# You can name this whatever you want
name: update

# You will get an error on the automatic updates committing
# if you do not have this line
# You didn't need it before, which is why a lot of yml job files
# you see will not have it (but you need it now!!!)
permissions:
  contents: write

# The 'on' section is about when this is run
# workflow_dispatch makes there be a button on GitHub to let you run it manually
# schedule and cron make it run at certain frequencies
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:


jobs:
  forecast-update:
    name: python
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.2"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync

      - name: Update realtime
        run: uv run python -m src.wind_forecast_ui --update realtime
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DAY_OF_WEEK: Monday

      - name: Commit and push any changes
        run: |-
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
